project:
  type: website
  output-dir: docs

format:
  html:
    theme: lumen
    mainfont: "Source Sans Pro, sans-serif"
    fontsize: 1rem
    css: styles.css

website:
  title: "AI4103: ML Systems"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: readings.qmd
        text: Readings
